apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:  #these are deployment labels
    app: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels: #this are pod labels
        app: app1
    spec:
      containers:
      - name: app1
        image: nishaldevops/app1:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  selector:
    app: app1
    project: roboshop
    component: frontend
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80 # this port belongs to service
    targetPort: 80 # this port belongs to container
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: app1
    annotations:
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/tags: Environment=dev,Project=roboshop
        alb.ingress.kubernetes.io/group.name: nishaldevops
spec:
  ingressClassName: alb
  rules:
  - host: "app1.nishaldevops.online"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app1
            port:
              number: 80
